version: '3.7'
services:
  mongodb:
    build:
      dockerfile: mongo.dockerfile
      context: ..
    image: tutum/mongodb
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: starwars
      MONGODB_USER: italo
      MONGODB_PASS: 123456789
