version: '3.7'
services:
  mongodb:
    build:
      dockerfile: mongo.dockerfile
      context: ..
    image: tutum/mongodb
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: starwars
      MONGO_INITDB_ROOT_USERNAME: italo
      MONGO_INITDB_ROOT_PASSWORD: 123456789
